routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\LoginController@showLoginForm')->middleware('guest');

Route::post('logout','Auth\LoginController@logout')->name('logout');
Route::get('logout','Auth\LoginController@logout')->name('logout');

Route::post('login','Auth\LoginController@login')->name('login');

Route::view('change-password','auth.passwords.reset');
Route::get('change-password/{id?}','Auth\LoginController@FormResetPass')->name('change-password');
Route::post('reset-password/{user_id?}','Auth\LoginController@resetPass')->name('reset-password');

Route::resource('expedients','ExpedientController');


//Route::group(['middleware' => 'auth'], function () {
  //
  //

/**
 * Rutas del Expediente
 */
Route::resource('expedients','ExpedientController');
Route::get('expedients/assign/list', ['as' => 'expedients.assign.list', 'uses' => 'ExpedientController@indexAssign']);
Route::get('expedients/search/list', ['as' => 'expedients.search.list', 'uses' => 'ExpedientController@indexSearch']);
// pases
Route::get('expedients/{expedient_id}/pass', ['as' => 'expedients.pass', 'uses' => 'ExpedientController@pass']);
Route::post('expedients/{expedient_id}/pass', ['as' => 'expedients.pass.confirmed', 'uses' => 'ExpedientController@passConfirmed']);
// reasignacion
Route::get('expedients/{expedient_id}/reassignPass', ['as' => 'expedients.reassignPass', 'uses' => 'ExpedientController@reassignPass']);
Route::post('expedients/{expedient_id}/reassignConfirmed', ['as' => 'expedients.reassign.confirmed', 'uses' => 'ExpedientController@reassignConfirmed']);
// recepcion
Route::get('expedients/{expedient_id}/receive', ['as' => 'expedients.receive', 'uses' => 'ExpedientController@receive']);
Route::get('expedients/{expedient_id}/rechazar',['as' => 'expedients.rechazar', 'uses' => 'ExpedientController@rechazar']);
Route::post('expedients/{expedient_id}/rechazar', ['as' => 'expedients.rechazado', 'uses' => 'ExpedientController@rechazado']);
// ingreso/egreso
Route::get('expedients/ingress/now', ['as' => 'expedients.ingress', 'uses' => 'ExpedientController@ingress']);
Route::get('expedients/{expedient_id}/ingress/confirmed', ['as' => 'expedients.ingress.confirmed', 'uses' => 'ExpedientController@ingressConfirmed']);
Route::post('expedients/{expedient_id}/ingress/confirmed', ['as' => 'expedients.ingress.confirmed', 'uses' => 'ExpedientController@ingressConfirmedTrue']);
Route::get('expedients/{expedient_id}/egress', ['as' => 'expedients.egress', 'uses' => 'ExpedientController@egress']);
Route::post('expedients/{expedient_id}/egress/confirmed', ['as' => 'expedients.egress.confirmed', 'uses' => 'ExpedientController@egressConfirmed']);
// archivo
Route::post('expedients/{id}/file', ['as' => 'expedient.file', 'uses' => 'ExpedientController@addfile']);
Route::get('expedients/{id}/file/{file_id}', ['as' => 'expedients.file.download', 'uses' => 'ExpedientController@download']);
Route::get('expedients/{expedient_id}/file/{file_id}/destroy', ['as' => 'expedients.file.destroy', 'uses' => 'ExpedientController@destroyFile']);
// Novedades
Route::get('expedient/{id}/novelties',['as' => 'expedient.novelties','uses' => 'NoveltyController@index']);
Route::get('expedient/{id}/novelty',['as' => 'expedient.novelty.create','uses' => 'NoveltyController@create']);
Route::post('expedient/{id}/novelty',['as' => 'expedient.novelty.store','uses' => 'NoveltyController@store']);
Route::get('expedient/novelty/{id}',['as' => 'expedient.novelty.edit','uses' => 'NoveltyController@edit']);
Route::post('expedient/novelty/{id}',['as' => 'expedient.novelty.update','uses' => 'NoveltyController@update']);
// Movimientos
Route::get('expedients/{id}/movements', ['as' => 'expedient.movements', 'uses' => 'MovementController@index']);
// Solo Letura
Route::get('expedients/{id}/show/read', ['as' => 'expedients.show.readOnly', 'uses' => 'ExpedientController@readOnly']);

/**
 * Files
 */
Route::resource('files','FileController');
/**
  * News
  */
Route::resource('novelties','NoveltyController');
/**
  * Movimientos
  */
Route::resource('movements','MovementController');
//
Route::resource('users','UserController');
//Auth::routes();
//});

//Route::get('/home', 'HomeController@index')->name('home');

resources/views/partials/head.blade.php
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Gestión Expedientes</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="/adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/adminlte/bower_components/font-awesome/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="/adminlte/bower_components/Ionicons/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/adminlte/dist/css/AdminLTE.min.css">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="/adminlte/dist/css/skins/_all-skins.min.css">

  @yield('link-styles')

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>

resources/views/partials/sidebar.blade.php
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
      <div class="pull-left image">
        {{-- <img src="/adminlte/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image"> --}}
      </div>
      <div class="pull-left image text-white">
        @if(Auth::user()->name)
          <p>{{Auth::user()->display_name}}</p>
          {{-- <a href="#"><i class="fa fa-circle text-success"></i> Online</a> --}}
        @endif
      </div>
    </div>
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu" data-widget="tree">
      <li class="header">MENU</li>
      <li class="treeview menu-open">
          <a href="#">
            <i class="fa fa-dashboard"></i> <span>Expedientes</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu" style="display: block;">
            @ability('ministro','expedient_assign')
              <li {{ (Request::is('*expedients/assign/list*') ? 'class=active' : '') }}>
                <a href="{{ route('expedients.assign.list') }}"><i class="fa fa-circle-o"></i>Listado</a>
              </li>
            @endability
            @permission('expedient_ingress')
              <li {{ (Request::is('*expedients/ingress/now*') ? 'class=active' : '') }}>
                <a href="{{ route('expedients.ingress') }}"><i class="fa fa-circle-o"></i>Reingresar</a>
              </li>
            @endpermission

            @ability('coordinador,relator,coordinador superior','')
              <li {{ (Request::is('*expedients') ? 'class=active' : '') }}>
                <a href="{{ route('expedients.index') }}"><i class="fa fa-circle-o"></i>Mis Expedientes</a>
              </li>
            @endability
            <li {{ (Request::is('*expedients/search/list') ? 'class=active' : '') }}>
              <a href="{{ route('expedients.search.list') }}"><i class="fa fa-circle-o"></i>Consulta</a>
            </li>
          </ul>
      </li>
      @permission('user_list')
      <li {{ (Request::is('*users*') ? 'class=active' : '') }}><a href="{{ route('users.index') }}"><i class="fa fa-users"></i>Usuarios</a></li>
      @endpermission
    </ul>
  </section>
  <!-- /.sidebar -->
</aside>