routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\LoginController@showLoginForm')->middleware('guest');

Route::post('logout','Auth\LoginController@logout')->name('logout');
Route::get('logout','Auth\LoginController@logout')->name('logout');

Route::post('login','Auth\LoginController@login')->name('login');

Route::view('change-password','auth.passwords.reset');
Route::get('change-password/{id?}','Auth\LoginController@FormResetPass')->name('change-password');
Route::post('reset-password/{user_id?}','Auth\LoginController@resetPass')->name('reset-password');

Route::resource('expedients','ExpedientController');


//Route::group(['middleware' => 'auth'], function () {
  //
  //

/**
 * Rutas del Expediente
 */
Route::resource('expedients','ExpedientController');
Route::get('expedients/assign/list', ['as' => 'expedients.assign.list', 'uses' => 'ExpedientController@indexAssign']);
Route::get('expedients/search/list', ['as' => 'expedients.search.list', 'uses' => 'ExpedientController@indexSearch']);
// pases
Route::get('expedients/{expedient_id}/pass', ['as' => 'expedients.pass', 'uses' => 'ExpedientController@pass']);
Route::post('expedients/{expedient_id}/pass', ['as' => 'expedients.pass.confirmed', 'uses' => 'ExpedientController@passConfirmed']);
// reasignacion
Route::get('expedients/{expedient_id}/reassignPass', ['as' => 'expedients.reassignPass', 'uses' => 'ExpedientController@reassignPass']);
Route::post('expedients/{expedient_id}/reassignConfirmed', ['as' => 'expedients.reassign.confirmed', 'uses' => 'ExpedientController@reassignConfirmed']);
// recepcion
Route::get('expedients/{expedient_id}/receive', ['as' => 'expedients.receive', 'uses' => 'ExpedientController@receive']);
Route::get('expedients/{expedient_id}/rechazar',['as' => 'expedients.rechazar', 'uses' => 'ExpedientController@rechazar']);
Route::post('expedients/{expedient_id}/rechazar', ['as' => 'expedients.rechazado', 'uses' => 'ExpedientController@rechazado']);
// ingreso/egreso
Route::get('expedients/ingress/now', ['as' => 'expedients.ingress', 'uses' => 'ExpedientController@ingress']);
Route::get('expedients/{expedient_id}/ingress/confirmed', ['as' => 'expedients.ingress.confirmed', 'uses' => 'ExpedientController@ingressConfirmed']);
Route::post('expedients/{expedient_id}/ingress/confirmed', ['as' => 'expedients.ingress.confirmed', 'uses' => 'ExpedientController@ingressConfirmedTrue']);
Route::get('expedients/{expedient_id}/egress', ['as' => 'expedients.egress', 'uses' => 'ExpedientController@egress']);
Route::post('expedients/{expedient_id}/egress/confirmed', ['as' => 'expedients.egress.confirmed', 'uses' => 'ExpedientController@egressConfirmed']);
// archivo
Route::post('expedients/{id}/file', ['as' => 'expedient.file', 'uses' => 'ExpedientController@addfile']);
Route::get('expedients/{id}/file/{file_id}', ['as' => 'expedients.file.download', 'uses' => 'ExpedientController@download']);
Route::get('expedients/{expedient_id}/file/{file_id}/destroy', ['as' => 'expedients.file.destroy', 'uses' => 'ExpedientController@destroyFile']);
// Novedades
Route::get('expedient/{id}/novelties',['as' => 'expedient.novelties','uses' => 'NoveltyController@index']);
Route::get('expedient/{id}/novelty',['as' => 'expedient.novelty.create','uses' => 'NoveltyController@create']);
Route::post('expedient/{id}/novelty',['as' => 'expedient.novelty.store','uses' => 'NoveltyController@store']);
Route::get('expedient/novelty/{id}',['as' => 'expedient.novelty.edit','uses' => 'NoveltyController@edit']);
Route::post('expedient/novelty/{id}',['as' => 'expedient.novelty.update','uses' => 'NoveltyController@update']);
// Movimientos
Route::get('expedients/{id}/movements', ['as' => 'expedient.movements', 'uses' => 'MovementController@index']);
// Solo Letura
Route::get('expedients/{id}/show/read', ['as' => 'expedients.show.readOnly', 'uses' => 'ExpedientController@readOnly']);

/**
 * Files
 */
Route::resource('files','FileController');
/**
  * News
  */
Route::resource('novelties','NoveltyController');
/**
  * Movimientos
  */
Route::resource('movements','MovementController');
//
Route::resource('users','UserController');
//Auth::routes();
//});

//Route::get('/home', 'HomeController@index')->name('home');

app/Expedient.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Expedient extends Model
{

    protected $fillable = ['title','number','user_create_id','user_owner_id','year_id','type_id','state_id'];

    public function files(){
      return $this->hasMany('App\File');
    }

    public function user(){
      return $this->hasOne('App\User');
    }

    public function year(){
      return $this->belongsTo('App\Year');
    }

    public function passes()
    {
      return $this->hasMany('App\Pass');
    }

    public function movements()
    {
      return $this->hasMany('App\Movement');
    }

    public function type(){
      return $this->belongsTo('App\Type');
    }

    public function novelties()
    {
      return $this->hasMany('App\Novelty');
    }

    public function userOwner(){
      return $this->hasOne('App\User','id','user_owner_id');
    }

}

app/Http/Controllers/ExpedientController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;
//use Illuminate\Support\Facades\Crypt;
use Laracasts\Flash\Flash;
use Illuminate\Http\Response;
use Carbon\Carbon;
use Illuminate\Support\Collection as Collection;
use Auth;
use App\Expedient;
use App\File;
use App\TypeFile;
use App\Role;
use App\User;
use App\Type;
use App\Pass;
use App\State;
use App\Movement;
use App\Year;

class ExpedientController extends Controller
{

    public function __construct()
    {
      $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Auth::user()->hasRole('ministro')) {
          return redirect()->route('expedients.assign.list');
        }
      // permisos
        if( Auth::user()->can('expedient_list')){
          // traigo los exptedientes que le fueron asignados
         $expedients = Expedient::whereUserOwnerId(Auth::user()->id)
                                ->whereNotIn('state_id',[3])
                                ->get();
          // traigo los exptes que le fueron pasados
          // $expedients = Expedient::join("pass","expedients.id","=","pass.expedient_id")
          //               ->where('pass.user_receiver_id','=',Auth::user()->id)
          //               ->get();
          // dd($expedients[0]->passes()->get());

          //creo la variable $create para ocupar la misma vista en el caso de asignar y no mostrar el boton de crear exptes
          $create = false;
          return view('expedients.index')
                        ->withCreate($create)
                        ->withExpedients($expedients);
        }else {
          Flash::warning('no tiene permisos');
          return redirect()->back();
        }
    }

    public function indexAssign()
    {
      // Muestro los expedientes para dentro del sector y boton crear
        if( Auth::user()->can('expedient_create') || Auth::user()->hasRole('ministro')){
          //estado 3 = "Egreso" => expediente fuera de la dependencia
          $expedients = Expedient::WhereNotIn('state_id',[3])->get();
          return view('expedients.indexAssign')
                        ->withExpedients($expedients);
        }else {
          Flash::warning('no tiene permisos');
          return redirect()->back();
        }
    }

    public function indexSearch()
    {
      // Muestro los expedientes para dentro del sector y boton crear
      $expedients = Expedient::all();
      return view('expedients.indexSearch')
                      ->withExpedients($expedients);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

      if (!Auth::user()->can('expedient_create')) {
        //si no tiene permiso para creaer expedientes
        Flash::error('<strong> Permiso Denegado.-</strong>');
        return redirect()->back();
      }
      $usersOwner = User::whereNotIn('id',[1])->pluck('display_name','id');
      // $usersOwner = User::whereHas('roles', function($q){
      //   $q->where('name','relator');
      // })->pluck('display_name','id');

      $years = Year::pluck('number','id');
      $types = Type::pluck('name','id');
      $selected = Carbon::now()->format('Y');
      return view('expedients.create')
                      ->withYears($years)
                      ->withTypes($types)
                      ->withUserOwner($usersOwner)
                      ->withSelected($selected);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

      // control sobre la funcion
      if (!Auth::user()->can('expedient_create') ){
        abort(403);
      }
      // validaciones
      request()->validate([
        'title' => 'required|string|min:10',
        'number' => 'required',
      ]);

      $state_id = State::where('name','=','Creado')->first()->id;

      if ($request->user_owner_id == 0) {
        $owner = null;
      }else {
        $owner = $request->user_owner_id;
      }

      // si pasa la validacion creo el expte
      try {

        DB::beginTransaction();

          $expedient = Expedient::create([
            'number' => $request->input('number'),
            'title' => $request->input('title'),
            'year_id' => $request->input('year_id'),
            'type_id' => $request->input('type_id'),
            'user_create_id' => Auth::user()->id,
            'user_owner_id' => $owner,
            'state_id' => $state_id,
          ]);

          // si viene usuario genero el pase

            Pass::create([
              'expedient_id' => $expedient->id,
              'user_receiver_id' => $owner,
              'user_sender_id' => Auth::user()->id,
              'observation' => $request->input('observation'),
            ]);

        DB::commit();

        flash::success('Expediente creado Correctamente.-');
        return redirect('expedients');

      } catch (\Exception $e) {

        DB::rollback();

        flash::error('Fallo la creación del expte.-');
        return redirect('expedients');

      }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      // control sobre la funcion
      if (!Auth::user()->can(['expedient_show','expedient_show_admin'])){
        abort(403);
      }
      //$id =  Crypt::decrypt($id);

      $expedient = Expedient::find($id);
      $typeFiles = TypeFile::pluck('name','id');

      // la consutla es si el coordinador o superio pueda ver solo los Administrativos (esto es en caso de que quiera setear datos en la url)
      if (Auth::user()->hasRole(['coordinador','coordinador_superior'])) {
        //if ($expedient->type()->first()->name === 'Administrativo') {
          return view('expedients.show')
                      ->withExpedient($expedient)
                      ->withtypeFiles($typeFiles);
        // }
        // else {
        //   flash::error('El Expediente al que intenta ingresar no es Administrativo.-');
        //   return redirect('expedients');
        // }
      }
      else {
        if ($expedient->type()->first()->name != 'Administrativo') {
            return view('expedients.show')
                      ->withExpedient($expedient)
                      ->withtypeFiles($typeFiles);
        }
        else {
          flash::error('El Expediente al que intenta ingresar es Administrativo, no tiene permisos.-');
          return redirect('expedients');
        }
      }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function readOnly($id)
    {
      //$id =  Crypt::decrypt($id);

      $expedient = Expedient::find($id);
      $c = 1;
      return view('expedients.readOnly',compact('expedient','c'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      // control sobre la funcion
      if (!Auth::user()->can('expedient_edit') ){
        abort(403);
      }

      $expedient = Expedient::find($id);

      return view('expedients.edit')
        ->withExpedient($expedient)
        ->withYears(Year::pluck('number','id'))
        ->withTypes(Type::pluck('name','id'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      // control sobre la funcion
      if (!Auth::user()->can('expedient_edit') ){
        abort(403);
      }
      // validaciones
      request()->validate([
        'title' => 'required|string|min:10',
        'number' => 'required',
      ]);

      // si pasa la validacion creo el expte
      try {

        DB::beginTransaction();

          $expedient = Expedient::find($id);
          $expedient->title = $request->input('title');
          $expedient->number = $request->input('number');
          $expedient->year_id = $request->input('year_id');
          $expedient->type_id = $request->input('type_id');
          $expedient->user_create_id = Auth::user()->id;
          $expedient->save();

        DB::commit();
        flash::success('Se modificó satisfactoriamente el expediente.-');
        return redirect()->route('expedients.index');

      } catch (\Exception $e) {

        DB::rollback();

        flash::error('Fallo la modificación del expediente.-');
        return redirect('expedients');
      }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      // control sobre la funcion
      if (!Auth::user()->can('expedient_destroy') ){
        abort(403);
      }
      $expte = Expedient::find($id);
      $expte->movements()->delete();
      $expte->files()->delete();
      $expte->passes()->delete();
      $expte->novelties()->delete();
      $expte->delete();


      Flash::success('expediente eliminado correctamente');
      return redirect()->back();
    }

    /**
     ** Muestro el expte en cuestion para el Pase
     */
    public function pass($id)
    {
      $expedient = Expedient::find($id);
      // traigo los pases que no se recibieron aun
      $expte = $expedient->passes()->whereReceivedAt(null)->get();
      // si hay pases sin recibir
      if ($expte->count()) {
        Flash::warning('El expediente no fue recibido en una instancia anterior');
        return redirect()->back();

resources/views/expedients/create.blade.php
@extends('main')

@section('content')

<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title">Nuevo Expediente</h3>
    <!-- <div class="box-tools pull-right">
      <a href="{{ route('expedients.create') }}" class="btn btn-primary">+<span class="hidden-xs">Expte Nuevo</span></a>
    </div> -->
  </div>
  <div class="box-body">
    <form class="form-horizontal" method="POST" action="{{ route('expedients.store') }}">
      {{ csrf_field() }}

      <!-- Caratula -->
      <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
          <div class="col-md-8">
            {{ Form::label('title', 'Caratula*') }}
            {{ Form::text('title', null, ['class' => 'form-control']) }}
            {!! $errors->first('title', '<p class="help-block">:message</p>')  !!}
          </div>
      </div>

      <!-- Numero -->
      <div class="form-group{{ $errors->has('number') ? ' has-error' : '' }}">
          <div class="col-md-6">
            {{ Form::label('number', 'Número*') }}
            {{ Form::text('number', null, ['class' => 'form-control']) }}
            {!! $errors->first('number', '<p class="help-block">:message</p>')  !!}
          </div>
      </div>

      <!-- Año -->
      <div class="form-group">
        <div class="col-sm-6">
          <label class="control-label">Año*</label>
          <select class="form-control" name="year_id">
            @foreach ($years as $key => $value)
              @if($value == $selected)
                <option value="{{$key}}" selected>{{$value}}</option>
              @else
                <option value="{{$key}}">{{$value}}</option>
              @endif
            @endforeach
          </select>
        </div>
      </div>

      <!-- tipo expediente -->
      <div class="form-group">
        <div class="col-sm-6">
          <label class="control-label">Tipo Expte*</label>
          <select class="form-control" name="type_id">
            @foreach ($types as $key => $value)
              <option value="{{$key}}">{{$value}}</option>
            @endforeach
          </select>
        </div>
      </div>

      <!-- personal que tramita la causa -->
      <div class="form-group">
        <div class="col-sm-6">
          <label class="control-label">Asignar*</label>
          <select class="form-control" name="user_owner_id">
            @foreach ($userOwner as $key => $value)
              <option value="{{$key}}">{{$value}}</option>
            @endforeach
          </select>
        </div>
      </div>

      <div class="form-group{{ $errors->has('observation') ? ' has-error' : '' }}">
          <div class="col-md-6">
            {{ Form::label('observation', 'Observación') }}
            {{ Form::text('observation', null, ['class' => 'form-control']) }}
            {!! $errors->first('observation', '<p class="help-block">:message</p>')  !!}
          </div>
      </div>

      <div class="form-group">
        <div class="pull-right col-sm-2">
          <button type="submit" class="btn btn-success pull-right btn-block">Guardar y Pasar</button>
        </div>
        {{-- <div class="pull-right col-sm-2">
          <button type="submit" class="btn btn-primary pull-right btn-block">Guardar</button>
        </div> --}}
      </div>

    </form>
  </div>
  <!-- /.box-body -->
  <div class="box-footer">
    <div class="box box-danger">
          <div class="box-header with-border">
            <h4>Importante!</h4>
            <p>Los campos con (*) son  obligatorios.-</p>
            <!-- /.box-tools -->
          </div>
          <!-- /.box-header -->
    </div>
  </div>
  <!-- /.box-footer-->
</div>
<!-- /.box -->

@endsection

resources/views/expedients/edit.blade.php
@extends('main')

@section('content')

<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title">Editar Expediente</h3>
    {!! Form::open(array('route' => array('expedients.destroy', $expedient->id), 'method' => 'delete')) !!}
    <button onclick="
            if (!confirm('Se va a eliminar permanentemente el usuario')) {
                return false;
            }
            ;" class="btn btn-danger pull-right" type="submit" >Eliminar Expediente</button>
    {!! Form::close() !!}
  </div>
  <div class="box-body">
    <form class="form-horizontal" method="POST" action="{{ route('expedients.update',['id' => $expedient->id]) }}">
      {{ csrf_field() }}
      {{ method_field('PATCH') }}
      <div class="form-group">
        <label class="control-label col-sm-2" for="title">Caratula</label>
        <div class="col-sm-10">
          <input type="title" class="form-control" id="title" value="{{$expedient->title}}" name="title">
        </div>
      </div>
      <div class="form-group">
        <label class="control-label col-sm-2">Numero:</label>
        <div class="col-sm-6">
          <input type="text" class="form-control" id="number" value="{{$expedient->number}}" name="number">
        </div>
      </div>

      <div class="form-group">
        <label class="control-label col-sm-2">Año:</label>
        <div class="col-sm-6">
          <select class="form-control" name="year_id">
            @foreach ($years as $key => $value)
              @if($key == $expedient->year_id)
              <option value="{{$key}}" selected="{{$expedient->year_id}}">{{$value}}</option>
              @endif
              <option value="{{$key}}">{{$value}}</option>
            @endforeach
          </select>
        </div>
      </div>
      
      <div class="form-group">
        <label class="control-label col-sm-2">Tipo Expte:</label>
        <div class="col-sm-6">
          <select class="form-control" name="type_id">
            @foreach ($types as $key => $value)
              @if($key == $expedient->type_id)
                <option value="{{$key}}" selected="{{$expedient->type_id}}">{{$value}}</option>
              @else
                <option value="{{$key}}">{{$value}}</option>
              @endif
            @endforeach
          </select>
        </div>
      </div>

      <!-- personal que tramita la causa -->
      <!-- <div class="form-group">
        <label class="control-label col-sm-2">Instructor:</label>
        <div class="col-sm-6">
          <select class="form-control" name="user_id">
            <option value="1" selected>Juan Cruz</option>
            <option value="2">Gomez Carlos</option>
          </select>
        </div>
      </div> -->

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-6">
          <button type="submit" class="btn btn-primary pull-right btn-block">Guardar</button>
        </div>
      </div>
    </form>
  </div>
  <!-- /.box-body -->
  <div class="box-footer">

  </div>
  <!-- /.box-footer-->
</div>
<!-- /.box -->

@endsection

resources/views/expedients/egress.blade.php
@extends('main')

@section('content')
<!-- Default box -->
<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title"><strong>Dar Salida expediente  </strong> <span class="text-info">"{{$expedient->number}}/{{$expedient->year->number}} {{$expedient->title}}"</span> </h3>
  </div>
  <div class="box-body">
      {!! Form::model($expedient, ['route' => ['expedients.egress.confirmed', $expedient->id]]) !!}
      <div class="row">
        <div class="form-group{{ $errors->has('observation') ? ' has-error' : '' }}">
          <div class="col-md-10">
            {{ Form::label('observation', 'Observación', ['class' => 'control-label']) }}
            {{ Form::textarea('observation', '', ['class' => 'form-control', 'rows' => 3, 'cols' => 20,'style' => 'resize:none']) }}
              {!! $errors->first('observation', '<p class="help-block">:message</p>')  !!}
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-offset-8 col-md-2">
            {{ Form::submit('Salida',['class'=>'form-control btn btn-success']) }}
          </div>
        </div>
      </div>
      {!! Form::close() !!}
  </div>
  <!-- /.box-body -->
  <div class="box-footer">
  </div>
  <!-- /.box-footer-->
</div>
<!-- /.box -->



@endsection

resources/views/expedients/indexSearch.blade.php
@extends('main')

@section('link-styles')
  <!-- DataTables -->
  <link rel="stylesheet" href="/adminlte/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
@endsection

@section('content')
<!-- Default box -->
<div class="box">
  @include('flash::message')
  <div class="box-header with-border">
    <h3 class="box-title">Listado Expedientes</h3>
  </div>
  <div class="box-body">
    @if (Session::has('flash_notification.message'))
            <div class="alert alert-{{ Session::get('flash_notification.level') }}">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{ Session::get('flash_notification.message') }}
            </div>
    @endif
    <table class="table" id="expedients-list">
      <thead class="thead-light">
        <tr>
          <th scope="col">Caratula</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        @foreach ($expedients as $key => $expedient)
          <tr>
            <td>
              <b>{{$expedient->number}}/{{$expedient->year->number}} </b>
              "{{$expedient->title}}"
            </td>
            <td>
                <!--actions-->
                <div class="btn-group pull-right">
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">Acciones <span class="caret"></span></button>
                    <ul class="dropdown-menu" role="menu">
                      <li><a href="{{ route('expedients.show.readOnly',array('id' => $expedient->id)) }}">Cosultar</a></li>
                    </ul>
                </div>
                <!--end actions-->
            </td>
          </tr>
        @endforeach
      </tbody>
    </table>
    {{-- {{ $expedients->links() }} --}}
  </div>
  <!-- /.box-body -->
  <div class="box-footer">

  </div>
  <!-- /.box-footer-->
</div>
<!-- /.box -->

@section('script-js')

  <!-- DataTables -->
  <script src="/adminlte/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
  <script src="/adminlte/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

  <script>
  $(function () {

    $('#expedients-list').DataTable({

    })
  })
</script>
@endsection

@endsection

resources/views/expedients/show.blade.php
@extends('main')

@section('content')
  @permission(['files_upload','files_upload_admin'])
  <!-- Default box -->
  <div class="box box-pimary">
    <div class="box-header with-border">
      <h3 class="box-title"> Subir Documentos </h3>
    </div>
    <div class="box-body">

      <form method="POST" action="{{ route('expedient.file',['expedient_id'=>$expedient->id]) }}" accept-charset="UTF-8" enctype="multipart/form-data">
        {{ csrf_field() }}

        <div class="form-group{{ $errors->has('file') ? ' has-error' : '' }}">
          <div class="col-md-4">
            {{ Form::label('file', 'Archivo') }}
            {{ Form::file('file', null, ['class' => 'form-control']) }}
            {!! $errors->first('file', '<p class="help-block">:message</p>')  !!}
          </div>
        </div>

        <div class="form-group{{ $errors->has('typeFile_id') ? ' has-error' : '' }}">
          <div class="col-md-4">
            {{ Form::label('typeFile_id', 'Tipo Documento') }}
            {{ Form::select('typeFile_id', $typeFiles,null, ['class' => 'form-control']) }}
            {!! $errors->first('typeFile_id', '<p class="help-block">:message</p>')  !!}
          </div>
        </div>

        <div class="form-group{{ $errors->has('title_file') ? ' has-error' : '' }}">
          <div class="col-md-4">
            {{ Form::label('title_file', 'Titulo') }}
            {{ Form::text('title_file', null, ['class' => 'form-control']) }}
            {!! $errors->first('title_file', '<p class="help-block">:message</p>')  !!}
          </div>
        </div>

        <div class="form-group">
          <div class="col-md-12">
            {!! Form::submit('Guardar Cambios',['class' => 'btn btn-success pull-right ']) !!}
          </div>
        </div>


      </form>
    </div>
    <!-- /.box-body -->
    <div class="box-footer">

    </div>
    <!-- /.box-footer-->
  </div>
  <!-- /.box -->
  @endpermission


<!-- Default box -->
<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title">{{$expedient->number}}/{{$expedient->year->number}} "{{$expedient->title}}" </h3>
    <!-- <div class="box-tools pull-right">
      <a href="{{ route('files.create') }}" class="btn btn-primary">+<span class="hidden-xs">Nuevo Documento</span></a>
    </div> -->
  </div>
  <div class="box-body">
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th scope="col" class="col-md-1"></th>
          <th scope="col">Documento</th>
          <th scope="col">Tipo Documento</th>
        </tr>
      </thead>
      <tbody>
        <tr>
        @foreach ($expedient->files as $file)
            <td class="img img-responsive">
                <img src="{{ asset('img/'.$file->extension.'.png') }}" height="25" width="25" alt="">
            </td>
            <td>{{$file->title}}</td>
            <td>{{  $file->typeFile->name }}</td>
            <td>
                <!--actions-->
                <div class="btn-group pull-right">
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">Acciones <span class="caret"></span></button>
                    <ul class="dropdown-menu" role="menu">
                        @permission('files_download')
                        <li><a href="{{ route('expedients.file.download',array('id' => $expedient->id,'file_id'=>$file->id)) }}">Descargar</a></li>
                        @endpermission
                        @permission('files_destroy')
                        <li><a href="{{ route('expedients.file.destroy',array('id' => $expedient->id,'file_id'=>$file->id)) }}">Eliminar</a></li>
                        @endpermission
                    </ul>
                </div>
                <!--end actions-->
            </td>
          </tr>
        @endforeach
      </tbody>
    </table>
  </div>
  <!-- /.box-body -->
  <div class="box-footer">
  </div>
  <!-- /.box-footer-->
</div>
<!-- /.box -->


@endsection