routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\LoginController@showLoginForm')->middleware('guest');

Route::post('logout','Auth\LoginController@logout')->name('logout');
Route::get('logout','Auth\LoginController@logout')->name('logout');

Route::post('login','Auth\LoginController@login')->name('login');

Route::view('change-password','auth.passwords.reset');
Route::get('change-password/{id?}','Auth\LoginController@FormResetPass')->name('change-password');
Route::post('reset-password/{user_id?}','Auth\LoginController@resetPass')->name('reset-password');

Route::resource('expedients','ExpedientController');


//Route::group(['middleware' => 'auth'], function () {
  //
  //

/**
 * Rutas del Expediente
 */
Route::resource('expedients','ExpedientController');
Route::get('expedients/assign/list', ['as' => 'expedients.assign.list', 'uses' => 'ExpedientController@indexAssign']);
Route::get('expedients/search/list', ['as' => 'expedients.search.list', 'uses' => 'ExpedientController@indexSearch']);
// pases
Route::get('expedients/{expedient_id}/pass', ['as' => 'expedients.pass', 'uses' => 'ExpedientController@pass']);
Route::post('expedients/{expedient_id}/pass', ['as' => 'expedients.pass.confirmed', 'uses' => 'ExpedientController@passConfirmed']);
// reasignacion
Route::get('expedients/{expedient_id}/reassignPass', ['as' => 'expedients.reassignPass', 'uses' => 'ExpedientController@reassignPass']);
Route::post('expedients/{expedient_id}/reassignConfirmed', ['as' => 'expedients.reassign.confirmed', 'uses' => 'ExpedientController@reassignConfirmed']);
// recepcion
Route::get('expedients/{expedient_id}/receive', ['as' => 'expedients.receive', 'uses' => 'ExpedientController@receive']);
Route::get('expedients/{expedient_id}/rechazar',['as' => 'expedients.rechazar', 'uses' => 'ExpedientController@rechazar']);
Route::post('expedients/{expedient_id}/rechazar', ['as' => 'expedients.rechazado', 'uses' => 'ExpedientController@rechazado']);
// ingreso/egreso
Route::get('expedients/ingress/now', ['as' => 'expedients.ingress', 'uses' => 'ExpedientController@ingress']);
Route::get('expedients/{expedient_id}/ingress/confirmed', ['as' => 'expedients.ingress.confirmed', 'uses' => 'ExpedientController@ingressConfirmed']);
Route::post('expedients/{expedient_id}/ingress/confirmed', ['as' => 'expedients.ingress.confirmed', 'uses' => 'ExpedientController@ingressConfirmedTrue']);
Route::get('expedients/{expedient_id}/egress', ['as' => 'expedients.egress', 'uses' => 'ExpedientController@egress']);
Route::post('expedients/{expedient_id}/egress/confirmed', ['as' => 'expedients.egress.confirmed', 'uses' => 'ExpedientController@egressConfirmed']);
// archivo
Route::post('expedients/{id}/file', ['as' => 'expedient.file', 'uses' => 'ExpedientController@addfile']);
Route::get('expedients/{id}/file/{file_id}', ['as' => 'expedients.file.download', 'uses' => 'ExpedientController@download']);
Route::get('expedients/{expedient_id}/file/{file_id}/destroy', ['as' => 'expedients.file.destroy', 'uses' => 'ExpedientController@destroyFile']);
// Novedades
Route::get('expedient/{id}/novelties',['as' => 'expedient.novelties','uses' => 'NoveltyController@index']);
Route::get('expedient/{id}/novelty',['as' => 'expedient.novelty.create','uses' => 'NoveltyController@create']);
Route::post('expedient/{id}/novelty',['as' => 'expedient.novelty.store','uses' => 'NoveltyController@store']);
Route::get('expedient/novelty/{id}',['as' => 'expedient.novelty.edit','uses' => 'NoveltyController@edit']);
Route::post('expedient/novelty/{id}',['as' => 'expedient.novelty.update','uses' => 'NoveltyController@update']);
// Movimientos
Route::get('expedients/{id}/movements', ['as' => 'expedient.movements', 'uses' => 'MovementController@index']);
// Solo Letura
Route::get('expedients/{id}/show/read', ['as' => 'expedients.show.readOnly', 'uses' => 'ExpedientController@readOnly']);

/**
 * Files
 */
Route::resource('files','FileController');
/**
  * News
  */
Route::resource('novelties','NoveltyController');
/**
  * Movimientos
  */
Route::resource('movements','MovementController');
//
Route::resource('users','UserController');
//Auth::routes();
//});

//Route::get('/home', 'HomeController@index')->name('home');

app/Novelty.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Novelty extends Model
{
    protected $fillable = ['title','public','text','expedient_id','user_id'];

    public function expedient()
    {
      return $this->belongsTo('App\Expedient');
    }
    public function user()
    {
      return $this->belongsTo('App\User','user_id','id');
    }
}

app/Http/Controllers/NoveltyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Laracasts\Flash\Flash;
use Auth;

use App\Novelty;
use App\Expedient;

class NoveltyController extends Controller
{

    public function __construct()
    {
      $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($id)
    {
      $expedient = Expedient::findOrFail($id);
      $novelties = $expedient->novelties()->orderBy('created_at','desc')->get();

      return view('novelties.index',compact('novelties','expedient'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($id)
    {
      $expedient = Expedient::findOrFail($id);
      return view('novelties.create',compact('expedient'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store($id,Request $request)
    {
      $expedient = Expedient::findOrFail($id);
      //valido los campos requeridos
      request()->validate([
        'title' => 'required|string',
        'text' => 'required|string',
      ]);


      if ($request->estado) {
        $estado = true;
      }
      else {
        $estado = false;
      }

      $novelty = Novelty::create([
        'title' => $request->title,
        'expedient_id' => $id,
        'text' => $request->text,
        'public' => $estado,
        'user_id' => Auth::user()->id,
      ]);
      return redirect()->route('expedient.novelties',array('id' => $id,'expedient'=>$expedient));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $novelty = Novelty::findOrFail($id);
      return view('novelties.edit',compact('novelty'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

      //valido los campos requeridos
      request()->validate([
        'title' => 'required|string',
        'text' => 'required|string',
      ]);


      if ($request->estado) {
        $estado = true;
      }
      else {
        $estado = false;
      }

      $novelty = Novelty::findOrFail($id);
      $novelty->title = $request->title;
      $novelty->text = $request->text;
      $novelty->public = $estado;
      $novelty->user_id = Auth::user()->id;
      $novelty->update();

      return redirect()->route('expedient.novelties',array('id' => $novelty->expedient_id));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $novelty = Novelty::findOrFail($id);
      $expedient_id = $novelty->expedient_id;
      $novelty->delete();

      Flash::success('Eliminado correctamente');
      return redirect()->route('expedient.novelties',array('id' => $expedient_id));
    }
}

resources/views/novelties/create.blade.php
@extends('main')

@section('title')
  <div class="well well-sm panel panel-warning">
    <small>
      <strong>
        {{ $expedient->number }}/{{ $expedient->year()->first()->number }}
      </strong>
      "{{ $expedient->title }}"
     </small>
  </div>
@endsection

@section('content')
<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title">Nueva Novedad</h3>
  </div>
  <div class="box-body">
      {!! Form::open(array('route' => array('expedient.novelty.store','id'=>$expedient->id), 'method' => 'POST')) !!}

      <div class="row">
          <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
              <div class="col-md-10">
                  {!! Form::label('title', 'Titulo') !!}
                  {!! Form::text('title', null, ['class' => 'form-control']) !!}
                  {!! $errors->first('title', '<p class="help-block">:message</p>') !!}
              </div>
          </div>
      </div>
      <div class="row">
          <div class="form-group{{ $errors->has('text') ? ' has-error' : '' }}">
              <div class="col-md-10">
                  {!! Form::label('text', 'Novedad') !!}
                  {!! Form::textarea('text', null, ['id' => 'text','class' => 'form-control','cols'=>50,'rows'=>5]) !!}
                  {!! $errors->first('text', '<p class="help-block">:message</p>') !!}
              </div>
          </div>
      </div>
      <div class="row">
          <div class="form-group{{ $errors->has('estado') ? ' has-error' : '' }}">
              <div class="col-md-5">
                  {!! Form::label('estado', 'Publico') !!}
                  {!! Form::checkbox('estado', null,array('class'=>'form-control selectpicker')) !!}
                  {!! $errors->first('estado', '<p class="help-block">:message</p>') !!}
              </div>
          </div>
      </div>
      {!! Form::submit('Guardar Cambios',['class' => 'btn btn-success pull-right ']) !!}
      {!! Form::close() !!}
    </div>
    <!-- /.box-body -->
    <div class="box-footer">
      {{-- <div class="box box-danger">
            <div class="box-header with-border">
              <h4>Importante!</h4>
              <p></p>

              <!-- /.box-tools -->
            </div>
            <!-- /.box-header -->
      </div> --}}
    </div>
    <!-- /.box-footer-->
  </div>
@endsection

resources/views/novelties/edit.blade.php
@extends('main')

@section('content')

<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title">Editar Novedad</h3>
  </div>
  <div class="box-body">
      {!! Form::model($novelty, array('route' => array('expedient.novelty.update', $novelty->id), 'method' => 'POST')) !!}
      <div class="row">
          <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
              <div class="col-md-10">
                  {!! Form::label('title', 'Titulo') !!}
                  {!! Form::text('title', null, ['class' => 'form-control']) !!}
                  {!! $errors->first('title', '<p class="help-block">:message</p>') !!}
              </div>
          </div>
      </div>
      <div class="row">
          <div class="form-group{{ $errors->has('text') ? ' has-error' : '' }}">
              <div class="col-md-10">
                  {!! Form::label('text', 'Novedad') !!}
                  {!! Form::textarea('text', null, ['id' => 'text','class' => 'form-control','cols'=>50,'rows'=>5]) !!}
                  {!! $errors->first('text', '<p class="help-block">:message</p>') !!}
              </div>
          </div>
      </div>
      <div class="row">
          <div class="form-group{{ $errors->has('estado') ? ' has-error' : '' }}">
              <div class="col-md-5">
                  {!! Form::label('estado', 'Publico') !!}
                  {!! Form::checkbox('estado',null,$novelty->public) !!}
                  {!! $errors->first('estado', '<p class="help-block">:message</p>') !!}
              </div>
          </div>
      </div>
        {!! Form::submit('Guardar Cambios',['class' => 'btn btn-success pull-right ']) !!}
        {!! Form::close() !!}
    </div>
    <!-- /.box-body -->
    <div class="box-footer">

    </div>
    <!-- /.box-footer-->
  </div>
@endsection

resources/views/novelties/index.blade.php
@extends('main')

@section('link-styles')
  <link rel="stylesheet" href="/css/novelty/index.css">
@endsection
@section('title')
  <div class="well well-sm panel panel-warning">
    <small>
      <strong>
        {{ $expedient->number }}/{{ $expedient->year()->first()->number }}
      </strong>
      "{{ $expedient->title }}"
     </small>
  </div>
  @include('flash::message')
  <div class="box-tools pull-right">
    <a href="{{ route('expedient.novelty.create',array('id'=> $expedient->id)) }}" class="btn btn-primary">+<span class="hidden-xs">Cargar Novedad</span></a>
  </div>
@endsection

@section('content')

    {{-- si es privado, muestro solo al usuario que creo y al ministro --}}
    @foreach ($novelties as $novelty)
      @if (!$novelty->public)
        @if ($novelty->user_id == Auth::user()->id || Auth::user()->hasRole('ministro'))
          <ul class="timeline">
            <li>
              @if ($novelty->public)
                <div class="timeline-badge success"><i class="fa  fa-unlock-alt"></i></div>
              @else
                <div class="timeline-badge danger"><i class="fa  fa-lock"></i></div>
              @endif
              <div class="timeline-panel ">
                <div class="timeline-heading">
                  <h4 class="timeline-title">{{ $novelty->title }}</h4>
                </div>
                <div class="timeline-body">
                  <p>{!! $novelty->text !!}</p>
                  <p><small class="text-muted"><i class="glyphicon glyphicon-time"></i> {{ $novelty->created_at->format('d M Y H:m:s') }} - {{ $novelty->user()->first()->name }} </small></p>
                  <div class="btn-group pull-right">
                      {!! Form::open(array('url' => route('novelties.destroy', ['id' => $novelty->id]), 'onsubmit' => 'return confirmDelete()')) !!}
                      {{ method_field('DELETE') }}
                      <div class="btn-group btn-group-sm" role="group" aria-label="Small button group">
                        <a href="{{ route('expedient.novelty.edit',array('id'=>$novelty->id)) }}" class="btn btn-primary" name="button">Editar</a>
                        {!! Form::submit('eliminar',['class' => 'btn btn-danger'])!!}
                      </div>
                      {!! Form::close() !!}
                  </div>
                </div>
              </div>
            </li>
          </ul>
        @endif
      @else
        <ul class="timeline">
          <li>
            <div class="timeline-badge success"><i class="fa  fa-unlock-alt"></i></div>
            <div class="timeline-panel ">
              <div class="timeline-heading">
                <h4 class="timeline-title">{{ $novelty->title }}</h4>
              </div>
              <div class="timeline-body">
                <p>{{ $novelty->text }}</p>
                <p><small class="text-muted"><i class="glyphicon glyphicon-time"></i> {{ $novelty->created_at->format('d M Y H:m:s') }} - {{ $novelty->user()->first()->name }} </small></p>
                <div class="btn-group pull-right">
                    {!! Form::open(array('url' => route('novelties.destroy', ['id' => $novelty->id]), 'onsubmit' => 'return confirmDelete()')) !!}
                    {{ method_field('DELETE') }}
                    <div class="btn-group btn-group-sm" role="group" aria-label="Small button group">
                      <a href="{{ route('expedient.novelty.edit',array('id'=>$novelty->id)) }}" class="btn btn-primary" name="button">Editar</a>
                      {!! Form::submit('eliminar',['class' => 'btn btn-danger'])!!}
                    </div>
                    {!! Form::close() !!}
                </div>
              </div>
            </div>
          </li>
        </ul>
      @endif
    @endforeach

<script type="text/javascript">
  function confirmDelete() {
    return confirm('Seguro desea eliminar?');
  }
</script>

@endsection